### ISSUE TITLE
Github does not recognize the license

### ISSUE THREAD

**Issue by onox** [damaki/libkeccak#4]
Github does not recognize the license (it shows "View license" instead of "BSD-3-Clause" and no license information when you view the file) because of the different word wrapping.

You can easily fix this by editing the `LICENSE` file and the click on "Choose a license template" in the upper right corner and then choose "BSD 3-Clause "New" or "Revisded" License" on the left.

**Comment by damaki** [comment]
Hey, thanks for spotting that. I've updated the LICENSE file using the template as you suggested.
